default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['LA_LIGA_DBPASS'] %>
  host: localhost

development:
  <<: *default
  database: la-liga_development

test:
  <<: *default
  database: la-liga_test

production:
  <<: *default
  database: la-liga_production