# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: edb4d8b43aa122721cc0361fd91b7dfc1a02d3073136b690b91ae77b438712a6522d0b5b6f6f42fc6796c3956fffde96bcce3981faff8e983a596291e65804b7

test:
  secret_key_base: 59051a3680ad37c26ffeac795dc55a1770c50c70b20b701558aaad88a6615f471c27e2adace4356a375cc30b2572439046a86d6269437a8f4b248ad55c8d391c

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
