name: Changelog

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: awk '/^## /{if (found) exit; found=1} found' src/resources/markdown/changelog.md > CHANGELOG.md
      - run: gh release edit ${{ github.event.release.name }} --notes-file CHANGELOG.md
